### ISSUE TITLE
一直显示“登陆 ，使用 Github”

### ISSUE THREAD

**Issue by chenxuuu** [shalldie/git-comment#5]
右上角一直显示“登陆 ，使用 Github”

![图片](https://user-images.githubusercontent.com/10357394/80675806-f6263900-8ae7-11ea-8081-d2361764f035.png)

登陆后也是这样，无法评论

firefox

另外你网址证书过期了，是不是证书过期导致的？

**Comment by shalldie** [comment]
firefox 的跨域请求偶现报错，看了一下其它库也有这个问题，等有空再来详细看看啥原因吧

证书是过期了，打算换个域名 233
