### ISSUE TITLE
急急急。

### ISSUE THREAD

**Issue by 3030373635** [shalldie/git-comment#9]
大佬还在维护吗，控制台一堆红色。

**Comment by 3030373635** [comment]
要是可以删除评论就好了

**Comment by shalldie** [comment]
最近比较忙，所以最近几个月没关注这个仓，回复较晚，，，见谅

一堆红色大概你那时候网络不稳定，或者 github 服务不稳定吧。
删除可以考虑添加进去，需要先看下 github api 是否支持。
